apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: client
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: server
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 20Gi
  target:
    kind: StatefulSet
    name: mongodb
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-type: external
  target:
    kind: Service
    name: client

images:
- name: slotmachine-client
  newName: pkhamdee/slotmachine
  newTag: client-fb180b7c76e5dbbb17414aff80d79a3b4f99611b
- name: slotmachine-server
  newName: pkhamdee/slotmachine
  newTag: server-fb180b7c76e5dbbb17414aff80d79a3b4f99611b

commonLabels:
  environment: production
