apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment

images:
- name: slotmachine-client
  newName: pkhamdee/slotmachine
  newTag: client-944f82fe98faa1a4cd7c9fde6691ad38112ce463
- name: slotmachine-server
  newName: pkhamdee/slotmachine
  newTag: server-944f82fe98faa1a4cd7c9fde6691ad38112ce463

commonLabels:
  environment: development
