apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: slotmachine.10.38.206.19.sslip.io  #patches host to slotmachine.<dev-lb-ip>.sslip.io
  target:
    kind: Ingress
    name: client
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment

images:
- name: slotmachine-client
  newName: pkhamdee/slotmachine
  newTag: client-b06715fb34fbd73056994e81896b7b7e91c51a6d
- name: slotmachine-server
  newName: pkhamdee/slotmachine
  newTag: server-b06715fb34fbd73056994e81896b7b7e91c51a6d

commonLabels:
  environment: development
