apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: slotmachine.dev.example.com
  target:
    kind: Ingress
    name: client
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment

images:
- name: slotmachine-client
  newName: pkhamdee/slotmachine
  newTag: client-005bd96ef4dca06af6f8323c82345bb6e91f0c2d
- name: slotmachine-server
  newName: pkhamdee/slotmachine
  newTag: server-005bd96ef4dca06af6f8323c82345bb6e91f0c2d

commonLabels:
  environment: development
